# Generated by Django 5.0.6 on 2024-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_metadata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='combined_normalized_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
