# Generated by Django 5.0.6 on 2024-11-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_metadata_combined_normalized_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='combined_normalized_text',
        ),
        migrations.AddField(
            model_name='embedding',
            name='combined_normalized_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
