# Generated by Django 5.0.6 on 2024-11-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_remove_metadata_combined_normalized_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
